stages:
  - build

yuque-hook:
  stage: build
  script:
    - '/usr/bin/env bash $CI_BUILDS_DIR/ci/build.sh'
  only:
    refs:
      - /^[t|v]\d+\.\d+\.\d+$/
  except:
    - branches
  tags:
    - ecs
